# Generated by Django 4.2.18 on 2025-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(auto_created=True, blank=True, max_length=150, null=True, unique=True)),
                ('name_product', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=13)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'order_with_respect_to': 'name_product',
            },
        ),
    ]
