# Generated by Django 4.2.18 on 2025-02-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(auto_created=True, blank=True, max_length=150, null=True, unique=True)),
                ('name_store', models.CharField(max_length=150, unique=True)),
                ('unit_store', models.CharField(max_length=150)),
                ('quantity_store', models.DecimalField(decimal_places=2, max_digits=13)),
                ('price_store', models.DecimalField(decimal_places=2, max_digits=13)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'order_with_respect_to': 'name_store',
            },
        ),
    ]
