# Generated by Django 4.2.18 on 2025-02-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name_store',
            field=models.CharField(max_length=150),
        ),
    ]
