# Generated by Django 4.2.18 on 2025-02-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(default='mesa', max_length=150)),
                ('payment_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('payment_qr', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('payment_card', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('total_canceled', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('change', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='client.client')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
                'order_with_respect_to': 'date',
            },
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'TicketItem',
                'verbose_name_plural': 'TicketsItems',
                'db_table': 'ticket_item',
                'order_with_respect_to': 'product',
            },
        ),
    ]
