# Generated by Django 4.2.18 on 2025-02-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(default='mesa', max_length=150)),
                ('payment_cash', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
                ('payment_qr', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
                ('payment_card', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('total_canceled', models.DecimalField(decimal_places=2, max_digits=13)),
                ('change', models.DecimalField(decimal_places=2, max_digits=13)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
                'order_with_respect_to': 'date',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_product', models.IntegerField()),
                ('subtotal_product', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'db_table': 'detail',
                'order_with_respect_to': 'product',
            },
        ),
    ]
