# Generated by Django 4.2.18 on 2025-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='quantity_product',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_card',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_cash',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_qr',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=13),
            preserve_default=False,
        ),
    ]
