# Generated by Django 4.2.18 on 2025-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='order_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('qr', 'QR'), ('card', 'Tarjeta')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_type',
            field=models.CharField(choices=[('dine_in', 'Para servir en mesa'), ('takeaway', 'Para llevar')], default='dine_in', max_length=10),
        ),
    ]
