# Generated by Django 4.2.18 on 2025-02-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_detail_quantity_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_card',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_qr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_canceled',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
