# Generated by Django 4.2.18 on 2025-02-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_ticket_order_type_ticket_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='service_type',
            field=models.CharField(choices=[('dine_in', 'Para mesa'), ('takeaway', 'Para llevar')], default='dine_in', max_length=10),
        ),
    ]
