# Generated by Django 4.2.18 on 2025-03-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='flavor',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
