# Generated by Django 4.2.18 on 2025-03-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticketitem_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='flavor',
            field=models.CharField(default='', max_length=60),
        ),
    ]
