# Generated by Django 4.2.18 on 2025-03-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticketitem_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='flavor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
