# Generated by Django 4.2.18 on 2025-01-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venturi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price',
        ),
    ]
