# Generated by Django 4.2.18 on 2025-01-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venturi', '0002_rename_cost_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'clients', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(auto_created=True, blank=True, max_length=150, null=True, unique=True),
        ),
    ]
