# Generated by Django 4.2.18 on 2025-01-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venturi', '0003_alter_client_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
