# Generated by Django 4.2.18 on 2025-01-18 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venturi', '0004_alter_client_name_alter_client_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ticket', models.BooleanField(default=True)),
                ('break_down', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='venturi.client')),
            ],
            options={
                'verbose_name': 'output',
                'verbose_name_plural': 'output',
                'order_with_respect_to': 'order_date',
            },
        ),
        migrations.CreateModel(
            name='ProductOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('given_money', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
                ('return_money', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venturi.output')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venturi.product')),
            ],
            options={
                'verbose_name': 'product output',
                'verbose_name_plural': 'product output',
                'order_with_respect_to': 'created',
            },
        ),
    ]
