# Generated by Django 4.2.18 on 2025-01-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venturi', '0006_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='productoutput',
            name='output',
        ),
        migrations.RemoveField(
            model_name='productoutput',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='code',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.PositiveIntegerField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Output',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductOutput',
        ),
    ]
