# Generated by Django 4.2.18 on 2025-01-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venturi', '0007_delete_company_remove_productoutput_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
