# Generated by Django 4.2.18 on 2025-02-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(default='chocolate', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ice Cream Flavor',
                'verbose_name_plural': 'Ice cream Flavors',
                'db_table': 'flavor',
                'order_with_respect_to': 'flavor',
            },
        ),
    ]
