# Generated by Django 4.2.18 on 2025-02-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreamflavor',
            name='flavor',
            field=models.CharField(default='chocolate', max_length=20, unique=True),
        ),
    ]
