export const dataRows = [
  {
    id: 1,
    lastName: "Snow",
    name: "Jon",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 5,
  },
  {
    id: 2,
    lastName: "Lannister",
    name: "Cersei",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 15,
  },
  {
    id: 3,
    lastName: "Lannister",
    name: "Jaime",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 3,
  },
  {
    id: 4,
    lastName: "Stark",
    name: "Arya",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 5,
  },
  {
    id: 5,
    lastName: "Targaryen",
    name: "Daenerys",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 8,
  },
  {
    id: 6,
    lastName: "Melisandre",
    name: null,
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 4,
  },
  {
    id: 7,
    lastName: "Clifford",
    name: "Ferrara",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 1,
  },
  {
    id: 8,
    lastName: "Frances",
    name: "Rossini",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 5,
  },
  {
    id: 9,
    lastName: "Roxie",
    name: "Harvey",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 8,
  },
  {
    id: 10,
    lastName: "Clifford",
    name: "Ferrara",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 5,
  },
  {
    id: 11,
    lastName: "Frances",
    name: "Rossini",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 3,
  },
  {
    id: 12,
    lastName: "Roxie",
    name: "Harvey",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 1,
  },
];

export const cols = [
  { field: "id", headerName: "ID", width: 90, sortable: false },
  {
    field: "name",
    headerName: "Nombre",
    width: 150,
    // editable: true,
  },
  {
    field: "lastName",
    headerName: "Apellido",
    width: 150,
    // editable: true,
  },
  {
    field: "telephone",
    headerName: "Teléfono",
    type: "number",
    headerAlign: "center",
    align: "center",
    width: 150,
    // editable: false,
    sortable: false,
  },
  {
    field: "email",
    headerName: "Correo electrónico",
    width: 200,
    // editable: false,
    sortable: false,
  },
  {
    field: "points",
    headerName: "Puntos",
    width: 200,
    headerAlign: "center",
    align: "center",
    editable: false,
  },

  // {
  //   field: "fullName",
  //   headerName: "Full name",
  //   description: "This column has a value getter and is not sortable.",
  //   sortable: false,
  //   width: 160,
  //   valueGetter: (value, row) => `${row.firstName || ""} ${row.lastName || ""}`,
  // },
];

export const colProducts = [
  {
    field: "id",
    headerName: "ID",
    width: 200,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "name",
    headerName: "Nombre",
    width: 200,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "description",
    headerName: "Descripción del producto",
    width: 200,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "price",
    headerName: "Precio Bs.",
    width: 200,
    headerAlign: "center",
    align: "center",
  },
];

export const rowProducts = [
  {
    id: 1,
    name: "Acai simple",
    description: "una bola de helado, dulce de leche",
    price: "25",
  },
  {
    id: 2,
    name: "Helado doble",
    description: "Dos porciones de helados, con toping, cobertura y galleta",
    price: "18",
  },
  {
    id: 3,
    name: "Ensalada de frutas",
    description: "frutas manzana, papaya, banana, yogurt",
    price: "12",
  },
  {
    id: 4,
    name: "Frappe",
    description: "hielo triturado, leche, oreo o café",
    price: "5",
  },
  {
    id: 5,
    name: "Capuccino",
    description: "Dos porciones de helados, con toping, cobertura y galleta",
    price: "18",
  },
  {
    id: 6,
    name: "brownie",
    description: "Dos porciones de helados, con toping, cobertura y galleta",
    price: "18",
  },
];
