export const rows = [
  {
    id: 1,
    last_name: "Snow",
    name: "Jon",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 5,
  },
  {
    id: 2,
    last_name: "Lannister",
    name: "Cersei",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 15,
  },
  {
    id: 3,
    last_name: "Lannister",
    name: "Jaime",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 3,
  },
  {
    id: 4,
    last_name: "Stark",
    name: "Arya",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 5,
  },
  {
    id: 5,
    last_name: "Targaryen",
    name: "Daenerys",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 8,
  },
  {
    id: 6,
    last_name: "Melisandre",
    name: null,
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 4,
  },
  {
    id: 7,
    last_name: "Clifford",
    name: "Ferrara",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 1,
  },
  {
    id: 8,
    last_name: "Frances",
    name: "Rossini",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 5,
  },
  {
    id: 9,
    last_name: "Roxie",
    name: "Harvey",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 8,
  },
  {
    id: 10,
    last_name: "Clifford",
    name: "Ferrara",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 5,
  },
  {
    id: 11,
    last_name: "Frances",
    name: "Rossini",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 3,
  },
  {
    id: 12,
    last_name: "Roxie",
    name: "Harvey",
    telephone: 75864925,
    email: "prueba@gmail.com",
    points: 1,
  },
];

export const columns = [
  { field: "id", headerName: "ID", width: 90, sortable: false },
  {
    field: "name",
    headerName: "Nombre",
    width: 150,
    // editable: true,
  },
  {
    field: "last_name",
    headerName: "Apellido",
    width: 150,
    // editable: true,
  },
  {
    field: "telephone",
    headerName: "Teléfono",
    type: "number",
    headerAlign: "center",
    align: "center",
    width: 150,
    // editable: false,
    sortable: false,
  },
  {
    field: "email",
    headerName: "Correo electrónico",
    width: 200,
    // editable: false,
    sortable: false,
  },
  {
    field: "points",
    headerName: "Puntos",
    width: 200,
    headerAlign: "center",
    align: "center",
    editable: false,
  },

  // {
  //   field: "fullName",
  //   headerName: "Full name",
  //   description: "This column has a value getter and is not sortable.",
  //   sortable: false,
  //   width: 160,
  //   valueGetter: (value, row) => `${row.firstName || ""} ${row.last_name || ""}`,
  // },
];
