export const columns = [
  { field: "id", headerName: "ID", width: 90, sortable: false },
  {
    field: "date",
    headerName: "Fecha de venta",
    width: 150,
    // editable: true,
    sortable: true,
  },
  {
    field: "time",
    headerName: "Hora",
    width: 150,
    // editable: true,
    sortable: true,
  },
  {
    field: "client",
    headerName: "Cliente",
    width: 150,
    // editable: true,
    sortable: true,
  },
  {
    field: "service_type",
    headerName: "Servicio",
    width: 150,
    // editable: true,
    sortable: true,
  },
  {
    field: "payment_cash",
    headerName: "Efectivo",
    width: 150,
    // editable: true,
    sortable: true,
  },
  {
    field: "payment_qr",
    headerName: "QR",
    width: 150,
    // editable: true,
  },
  {
    field: "total_amount",
    headerName: "total Fact. Bs.",
    type: "number",
    headerAlign: "center",
    align: "center",
    width: 150,
    // editable: false,
    sortable: true,
  },
  {
    field: "total_canceled",
    headerName: "Total cancelado",
    width: 200,
    // editable: false,
    sortable: false,
  },
  {
    field: "change",
    headerName: "Cambio",
    width: 200,
    // editable: false,
    sortable: false,
  },
  {
    field: "actions",
    type: "actions",
    headerName: "Acciones",
    cellClassName: "actions",
  },
];
