export const colStore = [
  { field: "id", headerName: "ID", width: 90, sortable: false },
  {
    field: "date",
    headerName: "Fecha",
    width: 150,
    // editable: true,
    sortable: true,
  },
  {
    field: "name",
    headerName: "Nombre",
    width: 150,
    // editable: true,
    sortable: true,
  },
  {
    field: "quantity",
    headerName: "Cantidad",
    width: 150,
    // editable: true,
  },
  {
    field: "price",
    headerName: "Precio Bs.",
    type: "number",
    headerAlign: "center",
    align: "center",
    width: 150,
    // editable: false,
    sortable: true,
  },
  {
    field: "subtotal",
    headerName: "Subtotal",
    width: 200,
    // editable: false,
    sortable: false,
  },
];

export const rowStore = [
  {
    id: 1,
    date: "21/02/2024",
    name: "Oreo",
    quantity: 4,
    price: 15,
    subtotal: 0,
  },
  {
    id: 2,
    date: "21/02/2024",
    name: "Banana",
    quantity: 12,
    price: 5,
    subtotal: 0,
  },
  {
    id: 3,
    date: "21/02/2024",
    name: "Papaya",
    quantity: 1,
    price: 8,
    subtotal: 0,
  },
  {
    id: 4,
    date: "21/02/2024",
    name: "Hielo",
    quantity: 6,
    price: 6,
    subtotal: 0,
  },
  {
    id: 5,
    date: "21/02/2024",
    name: "Frutilla",
    quantity: 4,
    price: 36,
    subtotal: 0,
  },
  {
    id: 6,
    date: "21/02/2024",
    name: "Vasos 300ml",
    quantity: 2,
    price: 11,
    subtotal: 0,
  },
  {
    id: 7,
    date: "21/02/2024",
    name: "Oreo",
    quantity: 4,
    price: 15,
    subtotal: 0,
  },
  {
    id: 8,
    date: "21/02/2024",
    name: "Oreo",
    quantity: 4,
    price: 15,
    subtotal: 0,
  },
  {
    id: 9,
    date: "21/02/2024",
    name: "Oreo",
    quantity: 4,
    price: 15,
    subtotal: 0,
  },
  {
    id: 10,
    date: "21/02/2024",
    name: "Oreo",
    quantity: 4,
    price: 15,
    subtotal: 0,
  },
  {
    id: 11,
    date: "21/02/2024",
    name: "Oreo",
    quantity: 4,
    price: 15,
    subtotal: 0,
  },
  {
    id: 12,
    date: "21/02/2024",
    name: "Oreo",
    quantity: 4,
    price: 15,
    subtotal: 0,
  },
];
